     
pragma solidity ^0.8.4;
// SPDX-License-Identifier: GPL-3.0-or-later
import "../IStorage.sol";

contract UnitStorage7 is IStorage{
    string[] public units;
    
    // set to onlyOwner()
    // check if value exists - 
    constructor(){
        //117
       units.push("As an architecture, the Economic Space Protocol\\u2019s approach to architecture is one where the protocol distributes records across a network of physical devices residing in different locations. There is no singular shared recording data structure, that is, the blockchain, but a network of nodes, each holding its records with remote references to those of others. Rather than relying on secrecy through cryptographically encoded records, it relies on privacy, where records start by being accessible only to their owner and located in the node where the owner created them. It is the owner who progressively shares them according to the logic of the network\\u2019s protocol. So in the network there are private records, shared records, public records, and everything in-between. The protocol connects these records through remote references, creating a physically distributed data structure instead of relying on a partially encrypted globally replicated linked list as its recording medium.");
       units.push("Agents can determine which of their records they share at any point in time through offers (smart-contract offers) that outline how the information may be used by and through the network.");
       units.push("There is no need to pre-determine the bounds of the information that the network can collectively store, leaving it a programming choice. This architecture is necessary for the Economic Space Protocol, and the economy it creates, as it keeps economic information private and economic instruments, distribution logics and performances, programmable. The architecture is thus very different to current blockchains and the token economies they enable.");
       units.push("Regulatory implications \\nThe Economic Space Protocol does not rely on a discourse in which \\u2018regulatory authorities\\u2019 are to be evaded or avoided; instead, it empowers users by allowing them to determine key features of their agent\\u2019s behavior: how it should be constrained or regulated through protocol; what information to share, and what information to keep private.");
       units.push("Are tokens securities? \\nTokens in the Economic Space Protocol carry specific utility and are not passive investment vehicles. Although all agents in the network are issuers and holders, agents utilize tokens to enable their economic activity.[33] Tokens are functional and implement specific elements of the protocol.\\n\\n[33] For example, the liquidity token allows the user to exchange and clear commodity tokens. The stake token enables users to peer with others to create economic relationships through reciprocal mutual stakeholding.");
       units.push("Whether this will be subject to various states\\u2019 regulation remains to be seen. However, we expect regulation only to be applicable in the on-ramp and off-ramp between the new economic space and the conventional economy.");
       units.push("FROM CAPITALIST TO POSTCAPITALIST ECONOMY");
       units.push("DESIGNING AN ECONOMY");
       units.push("Is cryptoeconomy just a refinement and acceleration of a capitalist economy or can it create new economic space? It could be either or, indeed, both. The platforms that utilize blockchain and cryptographic technologies can be placed at the service of protocols that are essentially capitalist, or postcapitalist protocols that are conceived more cooperatively and commons-oriented - designed around shared aspirations, financial innovation and risking together. The technology permits both capitalist and postcapitalist versions to be designed centrally or in a distributed way. Importantly, framed this way, the postcapitalist agenda can be seen as no less practicable than a formally designed, distributed capitalism, and we can provide a clear depiction of _the difference_ between the two. In both cases, there are cost and speed advantages of cryptoeconomic platforms because of the absence of need for central clearing houses, and we already see large corporations and states adopting the technology for fast, reliable, low cost and accurate record keeping. But there is a politics here, too. The emergence of central bank digital currencies is a stark statement.[34] It is not essential for states to digitally replicate their current money, but they realize they need a foothold in the space of crypto.\\n\\n[34] The International Monetary Fund reports that, in 2022, 105 countries and currency unions are exploring central bank digital currencies (up from 35 in 2020; 19 of the richest 20 currencies are involved \\u2013 see Fanti et al (2022)).");
       units.push("We are proposing the protocols of a postcapitalist economy in full awareness that this is a political as well as a technological project and, for us, that means that our analysis must be based in the lessons of history.");
       units.push("Our proposition, as it unfolds, points to the need to re-think some basic economic questions. We are not just opening the possibility of addressing new goals, and proposing more efficient ways of getting there. That would be to suggest that we know the end point. Rather, our objective is about network processes without specifying particular outcomes and hence without claims to their efficiency or harmony. We want to build the protocol on which _narratives of the future_ can be built. We need to rethink what we mean by \\u2018production\\u2019 of value, where what constitutes \\u2018value\\u2019 is an open question, and where the motivations for engaging in, and staking, value creation are themselves as important as the outputs created. We need to reframe what markets are and what they could be as network relations without reference to profit and without a centralized operator. These dimensions will be revealed as the analysis unfolds.");
       units.push("AN ECONOMICS PRIMER");
       units.push("While we are proposing to build an economy that is new in many respects, we cannot do so in a social, intellectual or historical vacuum. We must note what we can learn from capitalist modes of calculation, and we must engage an audience which may not have considered the possibility of building an economy on principles other than those identified with capitalism.");
       units.push("Accordingly, we turn to some basic principles of capitalist economics and start to focus on the ways in which they might (and might not) articulate with the potentials of a cryptoeconomy. In particular, our agenda is to pick apart certain standard economic categories in a detailed way, to ensure that we don\\u2019t simply carry over concepts and approaches that will ultimately inhibit our project. But nor do we assume there is nothing to learn from the conventional knowledge. On the contrary, we need to blend the new with relevant lessons derived from the old.");
       units.push("Economics is a broad and contested discipline. It is also an old one, with Adam Smith\\u2019s _Wealth of Nations_ almost 250 years old, and Karl Marx\\u2019s economics 180 years old. Back then it was debated as \\u2018political economy,\\u2019 with a narrower discipline of \\u2018economics\\u2019 \\u2013 locking the social into a set of simplifying assumptions \\u2013 dating only from the late 19th century. That narrowing involved the emergence of \\u2018neo-classical\\u2019 economics which remains hegemonic, more than 100 years on. It has, of course, significantly evolved over the past century, but the approach to \\u2018the social\\u2019 has varied little. It reduces the social to a set of behavioral abstractions (protocols), generally idealizations (_homo economicus_ as their agent), which equate social goals with the operation of \\u2018free\\u2019 markets (businesses maximizing their profits; consumers maximizing their \\u2018utility\\u2019) and restrict the state\\u2019s role to market facilitation. Theoretical innovations have generally been about adding complexity (e.g. game theory) and exploring \\u2018distortions\\u2019 (e.g. asymmetrical information; behavioral deviations from _homo economicus_). It presents as an _orthodoxy_, quite unlike the rest of the social sciences that are conceived in continuous theoretical and methodological debate. Moreover, it is not merely an orthodoxy but, as a socially decisive discourse, it is _performative_: this theory of markets and _homo economicus_ are less an attempt to _describe society_, than an engineering effort to _remake society_ in its own image, predicated on the assumptions of individualism, self-interest and the universal aspiration of profitability articulated through (predominantly) market relations. It has the template for the kinds of people and interactions it wants and, if permitted to run, it will find and train players to behave according to its model. In the era of cryptoeconomics we can describe this engineering effort as building protocols of social performance.[35]\\n\\n[35] We already see, to quote Nick Land (2018, \\u00A72.653), if human beings are found to be irrational or incompetent or \\u2018lack the plasticity to compete in these terms, or revolt against the roles and templates being automatically laid-out for them, then artificial agencies \\u2013 \\u2018DAOs\\u2019 \\u2013 will be fabricated to play the game instead.\\u2019");
       units.push("But that orthodoxy is under new challenge, especially with the capacities of cryptocurrencies and cryptographically enabled distributed systems. We see the rise of a sub-discipline of \\u2018cryptoeconomics\\u2019 as a distinct field of analysis. However, we are concerned that the propositions of cryptoeconomics have so far engaged in a limited way in the social and political theory that lies behind their \\u2018alternative\\u2019 economics.[36]\\n\\n[36] For example, Nick Szabo tweeted about economists and programmers: \\u2018An economist or programmer who hasn\\u2019t studied much computer science, including cryptography, but guesses about it, cannot design or build a long-term successful cryptocurrency. A computer scientist and programmer who hasn\\u2019t studied much economics, but applies common sense, can.\\u2019 @NickSzabo4, March 23 2018 https://twitter.com/nickszabo4/status/977035747713675264");
       units.push("Generally, challenges to the orthodoxy depict themselves as \\u2018political economy,\\u2019 picking up on the 18th and 19th century recognition that economics and politics (the social) cannot be separated.");
       units.push("In modern usage, \\u2018political economy\\u2019 emerged in the 1950\\u2019s as part of a radical rejection of capitalist class relations. Some branches reached back to Marx\\u2019s propositions about the contradictions of capitalism and the emergence of a politicized working class to resist oppression, creating the way for a self-organizing society.");
       units.push("Others developed a political economy that focussed on reforms of the state intended to make society fairer, more equal and more sustainable. Rather than a revolutionary politics, these reformers advocated a social democratic state, often looking to Scandinavian societies as their model. Both schools of political economy lost potency in the 1980\\u2019s and 90\\u2019s.");
       // 135
    }
    function set(uint256 location, string calldata _unit) external {
        units[location] = _unit;
    }
    function getById(uint256 location) external override returns (string memory unit) {
        return units[location];
    }

}