     
pragma solidity ^0.8.4;
// SPDX-License-Identifier: GPL-3.0-or-later
import "../IStorage.sol";
contract UnitStorage19 is IStorage{
    string[] public units;
    
    // set to onlyOwner()
    // check if value exists - 
    constructor(){
        //346
       units.push("It is important to note that the \\u2018competitors\\u2019 in Keynes\\u2019 explanation are not the 100 faces in the \\u2018contest,\\u2019 but the readers/voters. The terms of the competition, Keynes continued, generated a distinctive voting logic: \\nIt is not a case of choosing those [faces] that, to the best of one\\u2019s judgment, are really the prettiest, nor even those that average opinion genuinely thinks the prettiest. We have reached the third degree where we devote our intelligences to anticipating what average opinion expects the average opinion to be. And there are some, I believe, who practise the fourth, fifth and higher degrees.");
       units.push("In application to the stock market, Keynes contended that investors were like the reader/voters, buying shares not based on any criteria of fundamental value, nor propositions about profit-making potential, but on investors\\u2019 perception of what they think other investors will buy. So nothing matters but opinions, and opinions on opinions, or what they think other investors think others investors believe is the average opinion of the value of the asset. In other words, it\\u2019s all a speculative bubble of popular opinion without substance and it\\u2019s destined to burst.");
       units.push("Some readers may see a parallel between Keynes\\u2019 beauty contest analogy and our depiction of the relation between staking and network determination of value. But that would be a misunderstanding.");
       units.push("The first thing to note is that Keynes\\u2019s analogy in application to the stock market is itself limited. It mis-places the role of the central authority. It inserts a discrete \\u2018prize,\\u2019 funded by a central authority, as the motive for playing, and the awarding of the prize ends the game. In the stock market, people may invest in response to popular opinion and may be \\u2018ahead\\u2019 or \\u2018behind\\u2019 on their balance sheets according to stock choice and timing. But over time the material basis of share prices will be revealed by what state-certified corporate accounts actually show to be the profit performances of companies. The state\\u2019s role is not as a prize-giver to attract short-term audience participation but as a rule-maker to ensure reliable data.");
       units.push("Second, a direct analogy with our network proposal is flawed. In Keynes\\u2019 beauty contest, the contestants are not the faces (as would be implied by the term \\u2018beauty contest\\u2019) but the newspaper readers/voters. With reciprocal staking, the analogy would be if the only people who can vote in the beauty contest are the 100 contestants; they can divide their votes into fractions, and there is no winner-takes-all \\u2018prize\\u2019: the prize is connectivity. So there is no \\u2018winning\\u2019 from voting for yourself and, directly or transitively, it is likely that everyone will be holding a partial vote for everyone else, so prizes are as much collective as individual.");
       units.push("If we think of the 100 people whose faces appear in the contest, each having their own ways of identifying facial attributes (their own measures of value), there will be built across the network not a speculative bubble but a system of facial recognition. Distributed determination of value is a system of network recognition of value.");
       units.push("Two years before Keynes\\u2019 _General Theory_ was published, the idea of fundamental value rose to new prominence with developments in the analytics of corporate accounts. Benjamin Graham and David Dodd published _Security Analysis_ (1934), introducing the concept of \\u2018value investing.\\u2019 Their work has been made famous in the 21st century by Warren Buffett.[98]\\n\\n[98] Graham was Warren Buffett\\u2019s teacher/mentor. Buffett has written an introduction to later editions of _Security Analysis_.");
       units.push("The approach they took was to look at the intrinsic worth, or long-term \\u2018fundamentals,\\u2019 of a company and not be distracted by short-term share price volatility. The fundamentals include measures like company performance, profit margins, asset values, debt levels, etc.. The investment proposition was to use data on these fundamentals to reach an overall valuation of the company. This was then a guide to whether current stock prices were \\u2018overpriced\\u2019 or \\u2018underpriced,\\u2019 with direct implications as to whether the stock should be bought or sold at its current price.");
       units.push("Each of these fundamentals depicted by Graham and Dodd in 1934 is generally defined by reference to a distinctly capitalist economy and, we contend, an early to mid 20th century capitalist economy. In the 21st century, most of the largest and fastest growing companies in the world, when measured by market capitalization \\u2013 such as Alphabet, Amazon, Apple, Microsoft and Tesla \\u2013 have share prices far in excess of what Graham and Dodd\\u2019s measures would recommend, and have done so for some time.[99] To label these prices as \\u2018speculative\\u2019 and \\u2018bubbles,\\u2019 especially when they have lasted so long, seems to be a misreading of underlying processes.\\n\\n[99] Tesla did not turn a profit between 2002 and 2019 yet its capital value was greater than Toyota, despite the fact that it produced less than 5 percent of the number of vehicles produced by Toyota.");
       units.push("We believe that these stocks are symptoms of a change in what we should understand by \\u2018intrinsic worth\\u2019 and \\u2018fundamentals.\\u2019 Two factors are critical here. One is that the intangible assets that dominate these companies\\u2019 balance sheets \\u2013 software patents and brands \\u2013 cannot easily be subject to Graham and Dodd\\u2019s measures.[100] The second factor is that investors in these iconic 21st century companies are not simply speculators, nor are they simply \\u2018factoring in\\u2019 environmental, social and governance (ESG) qualifiers to their profit-driven calculus.[101] Many are taking an intentional long-term position on the future of the economy and wider society. In a changing world, they are investing in intentional modes of change. They are signaling financially what they believe in and what they project the future economic frontiers to be. Neither Keynes\\u2019 depiction of speculation nor Graham and Dodd\\u2019s depiction of intrinsic value appear able to capture this motivation.\\n\\n[100] The proportion of these companies\\u2019 assets classified as intangible is: Alphabet, 73 percent; Amazon, 81 percent; Apple, 96 percent; Microsoft, 93 percent; and Tesla 94 percent. See Brand Finance (2022).\\n [101] Reference here is to the emergence of so-called ESG accounting to sit along profit and loss accounts. But as ESG accounts are scarcely quantified, they sit largely as ethical qualifiers to standard accounts; not as an alternative way of measuring.");
       units.push("For these reasons, we contend that stake and stake owners inside the network will not tend to behave the way Keynes described. But nor are the fundamentals the ones that Graham and Dodd described, for people\\u2019s social, political and emotional responses to network potential are themselves part of the fundamentals. Accordingly, the Economic Space Protocol provides the data required to construct measures related to affect in the network, and hence to undertake a fundamentals analysis informed by the critical role of affect. But it will be up to agents to compile these data in ways that generate meaning as well as prediction.");
       units.push("DIVIDENDS AND THE SURPLUS");
       units.push("\\u2018Surplus\\u2019 is one of those terms in economics with many meanings, and it is not appropriate that we should aspire to give the definitive meaning here. Nonetheless, it is a term we are using, and so it needs some clarification in the context in which it arises analytically.");
       units.push("In the financial language that frames our approach, a surplus is a spread. In neoclassical economics, focussed as it is on exchange relations, the surplus is in individual relations between buyers and sellers: it is the spread between the price a buyer/seller would have been willing to accept and the price at which they do accept an offer. In Marx, surplus value is a class-based spread between the value of labor power (approximately equal to the wage) and the new value created by current labor. Piero Sraffa\\u2019s (1960) adaptation of Marx, which has been an important underlying influence in our analysis, poses the surplus as the spread between the commodities used up in the process of production and the commodities created by the process of production. When we extend Sraffa from a commodity world to a financial world, the surplus is simply output values created that are not paid for. Non-payment is not about theft, but the capacity of human endeavor to create, such that inputs into production are not sufficient to account for the value of outputs.");
       units.push("The Sraffian depiction seems valuable because of its generality: the neo-classical depiction is simply about \\u2018bargains\\u2019 in trading \\u2013 a depiction without useful social meaning - and Marx\\u2019s is specific to capitalist relations between labor and capital. The Sraffian surplus includes Marx\\u2019s surplus, albeit that the emphasis is not on extractive relations (i.e. that one class produces the surplus and another owns it) but its analytical benefit is that it can describe also a surplus in market-based, commodity producing societies that are precapitalist (late feudal) and a postcapitalist (a \\u2018market socialist\\u2019[102]) economy. Sraffa\\u2019s ledgers resonate with those we describe in later chapters, and give us some tools to describe a postcapitalist surplus.\\n\\n[102] Sraffa was not particularly an advocate of \\u2018market socialism\\u2019: a term which arose in the context of the 1920s Socialist Calculation Debate which Hayek claimed to have mastered (see Chapter 2.4). The proposition here is simply that he describes a surplus that could be framed in the context of \\u2018market socialism.\\u2019");
       units.push("But Sraffa\\u2019s depiction also has an immediate limitation for our purpose, for it is explicitly a depiction of a surplus created in a non-monetary, commodity-producing economy (recall Sraffa\\u2019s major work is called _Production of Commodities by Means of Commodities_). If surplus is attributed to the human endeavor to create, then we should not presume that the creative outputs of that endeavor are only and always commodities produced for a market. We prefer the extended Sraffian conception of the surplus as \\u2018outputs not paid for,\\u2019 which gives us an open-ended framing of what constitutes an \\u2018output.\\u2019");
       units.push("When our analysis opens up the conception of value in a postcapitalist economy we can also define the surplus as a spread. In the performance evaluation framework (see Appendix 4.1) the surplus is the spread between the value of network performance inputs and outputs, where outputs are valued by the network evaluation of the social outcomes they generate. In the derivative framing (Appendix 5.2) this spread is the value of the swap.");
       units.push("At this stage of the analysis we are now in a position to clarify (somewhat) the surplus of the new economic space. The surplus will take the form of dividends on stake, so it is appropriate to repeat the depiction of a dividend from Chapter 5.3: \\nIt may be a share of output, or a share of the net revenue (outputs less the cost of inputs). It could be a financial return or a commodity output return, and those returns may accrue directly to the stakeholder or to some other agent nominated by the stakeholder, such as the commons (see Chapter 6). It could also give other rights; for example, rights to influence the future evolution of the performance, or it could give the stakeholder rights to build their own performance in connection with the performance they staked.");
       units.push("That list is open-ended: it can be whatever an agent\\u2019s performance specifies the intended dividend to be. Some part of these dividends are not surplus: they are the conditions of reproduction of the performances of stakeholders either directly (by being used as inputs in their performances) or indirectly, by being sold to enable the purchase of other inputs. Indeed, in the case of the commons, where outputs may be allocated for free, the existence of dividends may be significant for the stake price of the producer, and _that_ is essential to the reproduction of the producer\\u2019s performance. We cannot, _ex ante_, specify what fraction is surplus and what is necessary for reproduction.");
       // 364
    }
    function set(uint256 location, string calldata _unit) external {
        units[location] = _unit;
    }
    function getById(uint256 location) external override returns (string memory unit) {
        return units[location];
    }

}