     
pragma solidity ^0.8.4;
// SPDX-License-Identifier: GPL-3.0-or-later
import "../IStorage.sol";

contract UnitStorage11 is IStorage{
    string[] public units;
    
    // set to onlyOwner()
    // check if value exists - 
    constructor(){
        //193
       units.push("To build the conditions for a distributed postcapitalist economy it is clear that markets are integral: they are an essential source of information in a scalable, non-centralized system. But should an analysis of postcapitalism start with markets?[65] In Chapter 1 we contended that the Economic Space Protocol is centered on postcapitalist performances and the creation of collectively-defined meanings of value. Yet we are starting our exposition of this Protocol not with performances of new value creation but with processes of market exchange. This is not a matter of choice: it is the engineering foundation on which communication protocols must be built.\\n\\n[65] Those who oppose market relations (and generally also the adoption of token exchange) generally also advocate localism, where it is direct personal relationships, not in a record-keeping system that form the basis of trust. The inevitable neglect of the production process that cannot exist without scale is clear, so this perspective is not engaged in our analysis. Furthermore, local relations are never without their own power relations.");
       units.push("We share this entry point with Marx, in Volume 1 of _Capital_ (1867), who starts by establishing the principles of equivalence in exchange, denominated in units of labor time \\u2013 what he calls \\u2018simple exchange\\u2019 \\u2013 before he turns to the production of new value. Like Marx, we later return to exchange in a central role; now within the dynamics of an economy of investing and credit issuance (Chapter 9). Some, including supporters of Marxism, would say that this starting point is fraught with problems,[66] for building the dynamism and uncertainty of performances on top of a protocol of simple exchange is challenging. Performances and exchanges have different drivers: they are not an automatic fit. But it is where we start, and we must approach it knowingly, including appreciating the challenges it created for Marx.[67]\\n\\n[66] In Marxism, one way of depicting the so-called \\u2018transformation problem\\u2019 is the challenge of reconciling value defined in simple exchange with value defined in dynamic accumulation of capital.\\n [67] Critics of Marx would say that the need to reconcile every commodity\\u2019s value denominated in labor time with a market price is the technical flaw in Marx\\u2019s analysis: the so-called \\u2018transformation problem.\\u2019");
       units.push("In particular, it is important to recognize that the analysis in this chapter assumes a liquid market: that there are no impediments to transactions due to a lack of capacity to \\u2018buy\\u2019 (match an offer). This is a simplifying assumption to \\u2018get the analysis rolling.\\u2019 In Chapter 8 we return to issues of liquidity, in the context of bringing network credit into the analysis.");
       units.push("A challenge of starting with simple market exchange is that everyone thinks they know how exchange works, so our propositions will be read as just an idiosyncratic restatement of a familiar process. But this chapter is much more than a semantic re-framing of conventional depictions of markets: the explanation below opens up one face of the distinctive dynamics of the Economic Space Protocol. Just as exchange is different in gift societies from capitalist societies, so it is different in the new economic space. In this chapter, we address how market interactions have to be designed in order to be non-capitalist, scalable, with unique units of account and not centrally managed.");
       units.push("Here is a brief summary, with each word needing respecification in italics. Those who participate in _markets_ are _agents_ who interact in a _network_ and, through their interactions, create _economic space_. In these markets, _prices_ are disconnected from the presumption of pursuit of profit and instead express units of collectively-defined _network value_ (see Chapter 13.2). Transactions are confirmed by the transfer of _tokens_ on a network _ledger_, rather than exchanges of \\u2018money.\\u2019");
       units.push("One particular condition is elevated by this reframing. It is critical to dissociate collectively defined value from sales and hence expenditure/ revenue from sales. The new economic space must be able to attribute value to outputs produced for the commons, and those who produce collectively defined value for the commons must be able to receive a yield on their performance (as the condition of their reproduction). This means a network attribution of value for outputs that do not \\u2018go to market.\\u2019");
       units.push("AGENTS AND MARKETS");
       units.push("Most introductions to economics depict \\u2018individuals\\u2019 interacting as buyers and sellers in predominantly monetized markets. The Economic Space Protocol depicts \\u2018agents\\u2019 in tokenized markets. What\\u2019s the difference?");
       units.push("Agents \\nAn economic agent is a networking unit with a unique network identity, following a protocol that may be utilized by an individual person or a collection of individuals. An agent is defined by reference to membership of a network, and the rights they gain from and give to such a network much the way a \\u2018citizen\\u2019 is defined by reference to membership of a polity.[68] Through an agent, individuals can collectively relate in ways of their own design (the agent can be itself a network), but when the agent relates to the larger network of which it is one part (a network of networks), it does so with a singular identity and with the capacities of a single economic agent. The network in aggregate is therefore always a network of networks.\\n\\n[68] The contrast in both cases is with an individual defined autonomously, outside of social context.");
       units.push("Agents relate to the network via the creation and matching of offers, in basically the way individuals or firms in on-line markets for goods and labor tasks make offers. In the network language, the seller makes an offer and the buyer matches the offer. The word \\u2018match\\u2019 rather than \\u2018accept\\u2019 relates to the network process of pairing the two sides of an exchange transaction.[69] The purpose may be a one-off transaction but of more interest is the potential for on-going relations: to engage with other agents in _mutual value creation, mutual investing_ and _mutual provision of liquidity_: the three domains that define the postcapitalist token system we are designing. What distinguishes an agent in capitalism from one in a postcapitalist economy is the protocols by which they interact in a network.\\n\\n[69] Offers and matching are explained in more detail in Chapters 9 and 10.");
       units.push("Markets[70] \\nThe Economic Space Protocol starts with the social as a design object, and is modeled after a network: it specifies the terms and rules by which agents participate in \\u2018the social\\u2019 as coherent, networked behaviors. The issuance and matching of offers to a network \\u2013 the social relations between agents through the network - are, in the first instance, exchange relations and in this sense constitute a market. But they are also communication relations and in this sense constitute an economic messaging network. The generic exchange relations are defined in the protocols of commodity,[71] credit, and stake exchange. The generic communication relations defined in the protocol are messaging about what is produced, what is collectively accepted as clearing the credit, and collective investment intentions. These exchange messages are elaborated in Chapter 9.\\n\\n[70] See L\\u00F3pez J. \\u2018Market offers: Distributed trading protocol.\\u2019 http://marketoffers.manifold.one\\n [71] This is the first use of the term \\u2018commodity,\\u2019 which appears frequently in the following analysis. We define \\u2018commodities\\u2019 to include all outputs produced for, and recognized by, the network. It is not Marx\\u2019s use of the term, which associates commodities with capitalist production relations. There, commodity production has two dimensions: it is extractive, in the sense that commodities are produced by the workers and owned by the capitalist, and it is produced so as to be sold for a profit. This latter emphasis gives rise to the term \\u2018commodification,\\u2019 with more and more facets of social life converted into marketable opportunities for extraction. Our use of the term \\u2018commodity\\u2019 is more like Sraffa (1960) in his book _Production of Commodities by Means of Commodities_. There, commodities are all produced outputs. They are produced for a market, but they are not exchanged for money. This gives space for our proposition that commodities can be produced for the commons (without a price). Similarly, there can be no suggestion that our use of the term commodity is subject to a \\u2018fetishism\\u2019 of commodities, developed by Marx (1867) at the end Chapter 1 of Volume I of _Capital_, for this term, too, is capitalist-specific. In many analyses, the political response to fetishism is to take goods and services out of market relations. Our proposal is to change the nature of markets.");
       units.push("For a network, market relations are effective for scaling, distribution and interoperability, but agents may also engage in \\u2018subnetwork\\u2019 interactions that may not rely on markets. These may be \\u2018local\\u2019 and directly co-operative, and these relations could involve quite innovative financial contracts (such as a gift; ownership which decays to the commons, etc.). These are all design questions. But to scale beyond the local, and be quantifiably recognized by the network-at-large, there must be the adoption of the larger network\\u2019s units of account.");
       units.push("These relations are not conceived around conventionally-defined market \\u2018structures\\u2019 of competitive, monopolistic, etc.; nor are they conceived around means-ends strategies of agents understood as optimizing individuals. Rather, these relations are conceived around performances: creative, often cooperative, but always social, acts that embed the potential for future effects and future rewards for the performers.");
       units.push("ECONOMIC SPACE");
       units.push("Every economic space shares a common economic grammar or value calculus. Each individual economic space is a communication medium, where economic agents express, through offers and matching, participation in the pursuit of a shared network goal. The focus, therefore, is on shared knowledge or \\u2018expression\\u2019 which, in turn, can be used to continually redesign economic space, making it inherently adaptive in expressing what is valued.");
       units.push("Framed this way, an economic space is expressed in two dimensions: first in market exchanges (the creation and matching of offers), but noting that the interactions of exchange may not be motivated by either prices nor optimisation strategies; and secondly through performances, where agents take a position on their own and other agent\\u2019s proposals for future value creation. The focus here is an inter-temporal spread featuring risk, volatility and creativity. In performances it is these dimensions that animate the creation and matching of offers.");
       units.push("TOKENS AND DISTRIBUTED LEDGERS");
       units.push("Ledgers \\nLedgers take the form of a digital double entry database; in structure basically no different from a corporate ledger. What will be different is the categories in which ledgers are compiled and the conditions for the entry of quantities against those numbers (the questions of what counts and how it is counted). These will depend on the network\\u2019s unit of exchange.[72] The network\\u2019s ledger records multiple instruments/asset types represented in multiple accounts measured in terms of a shared unit of exchange, and thereby made commensurable with any other.\\n\\n[72] The formal explanation of a unit of exchange is developed in Chapter 7.");
       units.push("A token system based on distributed ledgers does not require the function of single, universally recognized means of exchange, only that a means of exchange is quantitatively recognisable (has an exchange rate; is commensurable) across a network, where ownership and valuation can be recorded on a verifiable ledger. The reach of any token comes from the extent of a network of ledger relations. Moreover, there need be no presumption that the one token type performs all the \\u2018standard\\u2019 money functions. Different money functions can be implemented through different protocols, and different token types can be better or worse at them.[73]\\n\\n[73] This issue is explored in Chapter 10.");
       // 211
    }
    function set(uint256 location, string calldata _unit) external {
        units[location] = _unit;
    }
    function getById(uint256 location) external override returns (string memory unit) {
        return units[location];
    }

}