pragma solidity ^0.8.4;
// SPDX-License-Identifier: GPL-3.0-or-later
import '../IStorage.sol';

contract UnitDescriptorNodewordsStorage2 is IStorage{
    string[] public unitDescriptorNodewords;
    
    // set to onlyOwner()
    // check if value exists - 
    constructor(){
        unitDescriptorNodewords.push("sensitive, performative");
		unitDescriptorNodewords.push("kybernetes, issuance");
		unitDescriptorNodewords.push("cryptoeconomic, dealer");
		unitDescriptorNodewords.push("moneyless, dealer");
		unitDescriptorNodewords.push("computational, medium");
		unitDescriptorNodewords.push("financial, message");
		unitDescriptorNodewords.push("potential, message");
		unitDescriptorNodewords.push("derivative, stakeholding");
		unitDescriptorNodewords.push("arbitrary, discourse");
		unitDescriptorNodewords.push("fungible, option");
		unitDescriptorNodewords.push("political, stability");
		unitDescriptorNodewords.push("sensitive, severality");
		unitDescriptorNodewords.push("virtual, meta");
		unitDescriptorNodewords.push("kybernetes, autonomy");
		unitDescriptorNodewords.push("local, option");
		unitDescriptorNodewords.push("expressive, swap");
		unitDescriptorNodewords.push("virtual, space");
		unitDescriptorNodewords.push("illiquid, cryptoeconomics");
		unitDescriptorNodewords.push("interoperable, trade");
		unitDescriptorNodewords.push("postcapitalistic, value");
		unitDescriptorNodewords.push("synthetic, dividual");
		unitDescriptorNodewords.push("renaissance of, interoperability");
		unitDescriptorNodewords.push("peer-to-peer, non-price");
		unitDescriptorNodewords.push("peer-to-peer, sign");
		unitDescriptorNodewords.push("semiotic, metapragmatics");
		unitDescriptorNodewords.push("linguistic, dividend");
		unitDescriptorNodewords.push("kybernetes, object");
		unitDescriptorNodewords.push("interoperable, agent");
		unitDescriptorNodewords.push("derivative, severality");
		unitDescriptorNodewords.push("financial, subjectivity");
		unitDescriptorNodewords.push("sensitive, collateral");
		unitDescriptorNodewords.push("cryptographic, sign");
		unitDescriptorNodewords.push("illiquid, cryptoeconomy");
		unitDescriptorNodewords.push("synthetic, liquidity");
		unitDescriptorNodewords.push("dividual, multitude");
		unitDescriptorNodewords.push("economic, long-volatility");
		unitDescriptorNodewords.push("copoetic, anti-oedipus");
		unitDescriptorNodewords.push("decentralized, money");
		unitDescriptorNodewords.push("intangible, gift");
		unitDescriptorNodewords.push("econautic, subjectivity");
		unitDescriptorNodewords.push("financial, subjectivity");
		unitDescriptorNodewords.push("informational, issuance");
		unitDescriptorNodewords.push("copoetic, offer-queue");
		unitDescriptorNodewords.push("computational, clearing");
		unitDescriptorNodewords.push("expressive, interest");
		unitDescriptorNodewords.push("peer-to-peer, liquidity");
		unitDescriptorNodewords.push("protocolized, arbitrage");
		unitDescriptorNodewords.push("derivative, surplus");
		unitDescriptorNodewords.push("sensitive, market");
		unitDescriptorNodewords.push("econautic, expression");
		unitDescriptorNodewords.push("informational, nakamoto");
		unitDescriptorNodewords.push("liquid, theory");
		unitDescriptorNodewords.push("political, cypherpunk");
		unitDescriptorNodewords.push("intangible, price");
		unitDescriptorNodewords.push("financial, liquidity");
		unitDescriptorNodewords.push("copoetic, non-price");
		unitDescriptorNodewords.push("decentralized, option");
		unitDescriptorNodewords.push("decentralized, intellect");
		unitDescriptorNodewords.push("moneyless, medium");
		unitDescriptorNodewords.push("semiotic, swap");
		unitDescriptorNodewords.push("decentralized, medium");
		unitDescriptorNodewords.push("cryptographic, surplus");
		unitDescriptorNodewords.push("linguistic, cryptoeconomy");
		unitDescriptorNodewords.push("potential, credit");
		unitDescriptorNodewords.push("economic, option");
		unitDescriptorNodewords.push("cryptographic, volatility");
		unitDescriptorNodewords.push("machinic, platform");
		unitDescriptorNodewords.push("potential, commons");
		unitDescriptorNodewords.push("interoperable, economy");
		unitDescriptorNodewords.push("local, sign");
		unitDescriptorNodewords.push("postcapitalistic, language");
		unitDescriptorNodewords.push("computational, clearing");
		unitDescriptorNodewords.push("stable, expression");
		unitDescriptorNodewords.push("econautic, interoperability");
		unitDescriptorNodewords.push("distributed, cryptoeconomy");
		unitDescriptorNodewords.push("non-fungible, econautics");
		unitDescriptorNodewords.push("computational, stake");
		unitDescriptorNodewords.push("composite, book");
		unitDescriptorNodewords.push("informational, medium");
		unitDescriptorNodewords.push("decentralized, intellect");
		unitDescriptorNodewords.push("economic, counter-gift");
		unitDescriptorNodewords.push("political, co-reference");
		unitDescriptorNodewords.push("virtual, copoesis");
		unitDescriptorNodewords.push("informational, ledger");
		unitDescriptorNodewords.push("sensitive, price");
		unitDescriptorNodewords.push("illiquid, cyber");
		unitDescriptorNodewords.push("dividual, optionality");
		unitDescriptorNodewords.push("renaissance of, dividend");
		unitDescriptorNodewords.push("virtual, interoperability");
		unitDescriptorNodewords.push("peer-to-peer, theory");
		unitDescriptorNodewords.push("decolonised, metric");
		unitDescriptorNodewords.push("semiotics of the, dealer");
		unitDescriptorNodewords.push("political, netting");
		unitDescriptorNodewords.push("metapragmatic, metric");
		unitDescriptorNodewords.push("postcapitalistic, information");
		unitDescriptorNodewords.push("financial, economy");
		unitDescriptorNodewords.push("political, stability");
		unitDescriptorNodewords.push("semiotics of the, metric");
		unitDescriptorNodewords.push("sensitive, subjectivity");
		unitDescriptorNodewords.push("distributed, risk");
		unitDescriptorNodewords.push("composite, anti-oedipus");
		unitDescriptorNodewords.push("semiotics of the, token");
		unitDescriptorNodewords.push("decentralized, metric");
		unitDescriptorNodewords.push("copoetic, deconstruction");
		unitDescriptorNodewords.push("peer-to-peer, surplus");
		unitDescriptorNodewords.push("liquid, autonomy");
		unitDescriptorNodewords.push("copoetic, sign");
		unitDescriptorNodewords.push("resilient, volatility");
		unitDescriptorNodewords.push("political, monocracy");
		unitDescriptorNodewords.push("postcapitalistic, exchange");
		unitDescriptorNodewords.push("potential, commons");
		unitDescriptorNodewords.push("resilient, economic space agent");
		unitDescriptorNodewords.push("cryptographic, postcapitalism");
		unitDescriptorNodewords.push("cryptographic, surplus");
		unitDescriptorNodewords.push("metapragmatic, postcapitalism");
		unitDescriptorNodewords.push("distributed, performative");
		unitDescriptorNodewords.push("moneyless, autonomy");
		unitDescriptorNodewords.push("fungible, cyber");
		unitDescriptorNodewords.push("potential, illiquidity");
		unitDescriptorNodewords.push("moneyless, asset");
		unitDescriptorNodewords.push("derivative, offer");
		unitDescriptorNodewords.push("cryptographic, bookkeeper");
		unitDescriptorNodewords.push("semiotic, capability");
		unitDescriptorNodewords.push("local, theology");
		unitDescriptorNodewords.push("non-fungible, economic space grammar");
		unitDescriptorNodewords.push("distributed, stability");
		unitDescriptorNodewords.push("illiquid, economic space agent");
		unitDescriptorNodewords.push("collective, sign");
		unitDescriptorNodewords.push("econautic, satoshi");
		unitDescriptorNodewords.push("kybernetes, deconstruction");
		unitDescriptorNodewords.push("virtual, non-price");
		unitDescriptorNodewords.push("renaissance of, spread");
		unitDescriptorNodewords.push("virtual, privacy");
		unitDescriptorNodewords.push("invisible, eros");
		unitDescriptorNodewords.push("machinic, token");
		unitDescriptorNodewords.push("computational, innovation");
		unitDescriptorNodewords.push("fungible, satoshi");
		unitDescriptorNodewords.push("decentralized, risk");
		unitDescriptorNodewords.push("financial, autonomy");
		unitDescriptorNodewords.push("political, swap");
		unitDescriptorNodewords.push("arbitrary, dealer");
		unitDescriptorNodewords.push("peer-to-peer, swap");
		unitDescriptorNodewords.push("invisible, performative");
		unitDescriptorNodewords.push("arbitrary, intellect");
		unitDescriptorNodewords.push("cryptographic, governance");
		unitDescriptorNodewords.push("dividual, governance");
		unitDescriptorNodewords.push("collective, dividend");
		unitDescriptorNodewords.push("kybernetes, economic space agent");
		unitDescriptorNodewords.push("postcapitalistic, optionality");
		unitDescriptorNodewords.push("decentralized, exchange");
		unitDescriptorNodewords.push("informational, cryptoeconomics");
		unitDescriptorNodewords.push("economic, postcapitalism");
		unitDescriptorNodewords.push("semiotic, gift");
		unitDescriptorNodewords.push("cryptoeconomic, discourse");
		unitDescriptorNodewords.push("renaissance of, economic space");
		unitDescriptorNodewords.push("stable, protocol");
		unitDescriptorNodewords.push("invisible, navigator");
		unitDescriptorNodewords.push("derivative, multitude");
		unitDescriptorNodewords.push("sensitive, long-volatility");
		unitDescriptorNodewords.push("economic, exchange");
		unitDescriptorNodewords.push("protocolized, money");
		unitDescriptorNodewords.push("collective, language");
		unitDescriptorNodewords.push("sensitive, credit");
		unitDescriptorNodewords.push("collective, sign");
		unitDescriptorNodewords.push("sensitive, deconstruction");
		unitDescriptorNodewords.push("semiotic, risk");
		unitDescriptorNodewords.push("economic, stability");
		unitDescriptorNodewords.push("derivative, anti-oedipus");
		unitDescriptorNodewords.push("semiotic, exchange");
		unitDescriptorNodewords.push("dividual, grammar");
		unitDescriptorNodewords.push("interoperable, medium");
		unitDescriptorNodewords.push("stable, market");
		unitDescriptorNodewords.push("decentralized, sign");
		unitDescriptorNodewords.push("derivative, co-emergence");
		unitDescriptorNodewords.push("machinic, offer");
		unitDescriptorNodewords.push("arbitrary, language");
		unitDescriptorNodewords.push("economic, commons");
		unitDescriptorNodewords.push("distributed, value");
		unitDescriptorNodewords.push("local, economic space protocol");
		unitDescriptorNodewords.push("dividual, innovation");
		unitDescriptorNodewords.push("intangible, dividend");
		unitDescriptorNodewords.push("arbitrary, medium");
		unitDescriptorNodewords.push("financial, capability");
		unitDescriptorNodewords.push("collective, economic virtual machine");
		unitDescriptorNodewords.push("invisible, token");
		unitDescriptorNodewords.push("local, discourse");
		unitDescriptorNodewords.push("invisible, dividend");
		unitDescriptorNodewords.push("informational, severality");
		unitDescriptorNodewords.push("intangible, knowledge");
		unitDescriptorNodewords.push("cryptoeconomic, metapragmatics");
		unitDescriptorNodewords.push("econautic, option");
		unitDescriptorNodewords.push("econautic, option");
		unitDescriptorNodewords.push("copoetic, economic space agency");
		unitDescriptorNodewords.push("semiotic, trade");
		unitDescriptorNodewords.push("informational, privacy");
		unitDescriptorNodewords.push("synthetic, netting");
		unitDescriptorNodewords.push("political, econaut");
		unitDescriptorNodewords.push("stable, commons");
		unitDescriptorNodewords.push("dividual, deconstruction");
		unitDescriptorNodewords.push("economic, value");
		unitDescriptorNodewords.push("composite, surplus");
		unitDescriptorNodewords.push("collective, stability");
		unitDescriptorNodewords.push("intangible, object");
		unitDescriptorNodewords.push("informational, grammar");
		unitDescriptorNodewords.push("protocolized, optionality");
		unitDescriptorNodewords.push("sensitive, finance");
		unitDescriptorNodewords.push("machinic, discourse");
		unitDescriptorNodewords.push("peer-to-peer, privacy");
		unitDescriptorNodewords.push("intangible, offer");
		unitDescriptorNodewords.push("nonlinear, clearing");
		unitDescriptorNodewords.push("cryptoeconomic, sense-maker");
		unitDescriptorNodewords.push("cryptoeconomic, satoshi");
		unitDescriptorNodewords.push("informational, nakamoto");
		unitDescriptorNodewords.push("moneyless, issuance");
		unitDescriptorNodewords.push("informational, meta");
		unitDescriptorNodewords.push("intangible, attractor");
		unitDescriptorNodewords.push("computational, innovation");
		unitDescriptorNodewords.push("local, meta");
		unitDescriptorNodewords.push("local, metric");
		unitDescriptorNodewords.push("collective, agency");
		unitDescriptorNodewords.push("econautic, arbitrage");
		unitDescriptorNodewords.push("invisible, money");
		unitDescriptorNodewords.push("linguistic, gift");
		unitDescriptorNodewords.push("semiotic, language");
		unitDescriptorNodewords.push("machinic, dealer");
		unitDescriptorNodewords.push("synthetic, money");
		unitDescriptorNodewords.push("informational, trade");
		unitDescriptorNodewords.push("synthetic, semiosis");
		unitDescriptorNodewords.push("local, metapragmatics");
		unitDescriptorNodewords.push("semiotics of the, spread");
		unitDescriptorNodewords.push("sensitive, semiosis");
		unitDescriptorNodewords.push("financial, dividual");
		unitDescriptorNodewords.push("renaissance of, privacy");
		unitDescriptorNodewords.push("informational, economy");
		unitDescriptorNodewords.push("collective, governance");
		unitDescriptorNodewords.push("expressive, cyber");
		unitDescriptorNodewords.push("sensitive, discourse");
		unitDescriptorNodewords.push("nonlinear, severality");
		unitDescriptorNodewords.push("financial, credit");
		unitDescriptorNodewords.push("derivative, non-price");
		unitDescriptorNodewords.push("composite, dividual");
		unitDescriptorNodewords.push("derivative, credit");
		unitDescriptorNodewords.push("fungible, liquidity");
		unitDescriptorNodewords.push("metapragmatic, navigator");
		unitDescriptorNodewords.push("machinic, counter-gift");
		unitDescriptorNodewords.push("semiotic, community");
		unitDescriptorNodewords.push("potential, cryptoeconomics");
		unitDescriptorNodewords.push("cryptographic, price");
		unitDescriptorNodewords.push("liquid, cryptoeconomics");
		unitDescriptorNodewords.push("machinic, risk");
		unitDescriptorNodewords.push("linguistic, anti-oedipus");
		unitDescriptorNodewords.push("intangible, privacy");
		unitDescriptorNodewords.push("peer-to-peer, navigator");
		unitDescriptorNodewords.push("derivative, trade");
		unitDescriptorNodewords.push("financial, interoperability");
		unitDescriptorNodewords.push("invisible, performance");
		unitDescriptorNodewords.push("semiotics of the, arbitrage");
		unitDescriptorNodewords.push("local, interface");
		unitDescriptorNodewords.push("stable, dividual");
		unitDescriptorNodewords.push("potential, theology");
		unitDescriptorNodewords.push("collective, language");
		unitDescriptorNodewords.push("illiquid, message");
		unitDescriptorNodewords.push("composite, metric");
		unitDescriptorNodewords.push("economic, commons");
		unitDescriptorNodewords.push("financial, counter-gift");
		unitDescriptorNodewords.push("postcapitalistic, stakeholding");
		unitDescriptorNodewords.push("nonlinear, stability");
		unitDescriptorNodewords.push("sensitive, finance");
		unitDescriptorNodewords.push("derivative, liquidity");
		unitDescriptorNodewords.push("intangible, metapragmatics");
		unitDescriptorNodewords.push("potential, trade");
		unitDescriptorNodewords.push("cryptographic, optionality");
		unitDescriptorNodewords.push("informational, account");
		unitDescriptorNodewords.push("decentralized, non-price");
		unitDescriptorNodewords.push("synthetic, platform");
		unitDescriptorNodewords.push("expressive, sense-maker");
		unitDescriptorNodewords.push("cryptoeconomic, multitude");
		unitDescriptorNodewords.push("collective, economic space agency");
		unitDescriptorNodewords.push("composite, space");
		unitDescriptorNodewords.push("econautic, economy");
		unitDescriptorNodewords.push("non-fungible, postcapitalism");
		unitDescriptorNodewords.push("invisible, discourse");
		unitDescriptorNodewords.push("composite, navigator");
		unitDescriptorNodewords.push("informational, economic space agent");
		unitDescriptorNodewords.push("sensitive, information");
		unitDescriptorNodewords.push("collective, attractor");
		unitDescriptorNodewords.push("copoetic, index");
		unitDescriptorNodewords.push("synthetic, grammar");
		unitDescriptorNodewords.push("expressive, innovation");
		unitDescriptorNodewords.push("economic, netting");
		unitDescriptorNodewords.push("cryptoeconomic, derivative");
		unitDescriptorNodewords.push("fungible, message");
		unitDescriptorNodewords.push("decentralized, theory");
		unitDescriptorNodewords.push("decentralized, swap");
		unitDescriptorNodewords.push("derivative, account");
		unitDescriptorNodewords.push("linguistic, interoperability");
		unitDescriptorNodewords.push("financial, object");
		unitDescriptorNodewords.push("arbitrary, severality");
		unitDescriptorNodewords.push("non-fungible, sense-maker");
		unitDescriptorNodewords.push("composite, option");
		unitDescriptorNodewords.push("linguistic, offer-queue");
		unitDescriptorNodewords.push("dividual, volatility");
		unitDescriptorNodewords.push("virtual, semiosis");
		unitDescriptorNodewords.push("potential, co-reference");
		unitDescriptorNodewords.push("distributed, intellect");
		unitDescriptorNodewords.push("distributed, econaut");
		unitDescriptorNodewords.push("informational, interface");
		unitDescriptorNodewords.push("decentralized, ledger");
		unitDescriptorNodewords.push("expressive, volatility");
		unitDescriptorNodewords.push("resilient, offer");
		unitDescriptorNodewords.push("linguistic, dividual");
		unitDescriptorNodewords.push("peer-to-peer, interoperability");
		unitDescriptorNodewords.push("distributed, right");
		unitDescriptorNodewords.push("cryptographic, economic space agency");
		unitDescriptorNodewords.push("interoperable, meta");
		unitDescriptorNodewords.push("collective, autonomy");
		unitDescriptorNodewords.push("synthetic, econautics");
		unitDescriptorNodewords.push("protocolized, account");
		unitDescriptorNodewords.push("economic, protocol");
		unitDescriptorNodewords.push("financial, trade");
		unitDescriptorNodewords.push("protocolized, agency");
		unitDescriptorNodewords.push("political, grammar");
		unitDescriptorNodewords.push("local, account");
		unitDescriptorNodewords.push("moneyless, token");
		unitDescriptorNodewords.push("semiotics of the, semiosis");
		unitDescriptorNodewords.push("cryptoeconomic, econaut");
		unitDescriptorNodewords.push("decentralized, agency");
		unitDescriptorNodewords.push("semiotics of the, autonomy");
		unitDescriptorNodewords.push("peer-to-peer, economic space agency");
		unitDescriptorNodewords.push("invisible, postcapitalism");
		unitDescriptorNodewords.push("local, information");
		unitDescriptorNodewords.push("distributed, information");
		unitDescriptorNodewords.push("kybernetes, derivative");
		unitDescriptorNodewords.push("arbitrary, token");
		unitDescriptorNodewords.push("distributed, price");
		unitDescriptorNodewords.push("virtual, capability");
		unitDescriptorNodewords.push("renaissance of, stakeholding");
		unitDescriptorNodewords.push("interoperable, grammar");
		unitDescriptorNodewords.push("semiotics of the, information");
		unitDescriptorNodewords.push("economic, trade");
		unitDescriptorNodewords.push("fungible, performative");
		unitDescriptorNodewords.push("virtual, security");
		unitDescriptorNodewords.push("copoetic, economic virtual machine");
		unitDescriptorNodewords.push("liquid, agency");
		unitDescriptorNodewords.push("potential, expression");
		unitDescriptorNodewords.push("collective, theory");
		unitDescriptorNodewords.push("dividual, message");
		unitDescriptorNodewords.push("protocolized, agency");
		unitDescriptorNodewords.push("semiotic, derivative");
		unitDescriptorNodewords.push("resilient, economic space agent");
		unitDescriptorNodewords.push("dividual, theory");
		unitDescriptorNodewords.push("financial, stakeholding");
		unitDescriptorNodewords.push("informational, stake");
		unitDescriptorNodewords.push("copoetic, economy");
		unitDescriptorNodewords.push("expressive, co-emergence");
		unitDescriptorNodewords.push("sensitive, bookkeeper");
		unitDescriptorNodewords.push("moneyless, capability");
		unitDescriptorNodewords.push("virtual, economic space agency");
		unitDescriptorNodewords.push("collective, monocracy");
		unitDescriptorNodewords.push("economic, anti-oedipus");
		unitDescriptorNodewords.push("potential, cypherpunk");
		unitDescriptorNodewords.push("cryptographic, navigator");
		unitDescriptorNodewords.push("postcapitalistic, economic space protocol");
		unitDescriptorNodewords.push("decolonised, satoshi");
		unitDescriptorNodewords.push("resilient, meta");
		unitDescriptorNodewords.push("non-fungible, anti-oedipus");
		unitDescriptorNodewords.push("moneyless, intellect");
		unitDescriptorNodewords.push("sensitive, dividend");
		unitDescriptorNodewords.push("liquid, economic virtual machine");
		unitDescriptorNodewords.push("distributed, option");
		unitDescriptorNodewords.push("machinic, stability");
		unitDescriptorNodewords.push("econautic, trade");
		unitDescriptorNodewords.push("moneyless, object");
		unitDescriptorNodewords.push("renaissance of, innovation");
    }
    function set(uint256 location, string calldata _unit) external {
        unitDescriptorNodewords[location] = _unit;
    }
    function getById(uint256 id) external override returns (string memory unit) {
		return unitDescriptorNodewords[id];
	}

    

}