pragma solidity ^0.8.4;
// SPDX-License-Identifier: GPL-3.0-or-later

contract ChapterStorageRemixTest{
    string[] public chapters;
    // remove getters in all StorageContracts
    // set to onlyOwner()
    // check if value exists - 
    constructor(){
        chapters.push("");
        chapters.push("Acknowledgment");
        chapters.push("Acknowledgment");
        chapters.push("Acknowledgment");
        chapters.push("Acknowledgment");
        chapters.push("Acknowledgment");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("13");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("Appendix 1.1");
        chapters.push("Appendix 1.1");
        chapters.push("Appendix 1.1");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("8");
        chapters.push("2");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
    }
    function set(uint256 location, string calldata _unit) external {
        chapters[location] = _unit;
    }
    //Returns the currently stored unsigned integer
    function get(uint256 location) public view returns (string memory) {
        return chapters[location];
    }

}