pragma solidity ^0.8.4;
// SPDX-License-Identifier: GPL-3.0-or-later
import "../IStorage.sol";
import { Ownable } from "@openzeppelin/contracts/access/Ownable.sol";

contract ChapterStorage1 is IStorage{
    string[] public chapters;
    
    // set to onlyOwner()
    // check if value exists - 
    constructor(){
        chapters.push("");
        //added missing unit
        chapters.push("Title");
        chapters.push("Acknowledgment"); // 1
        chapters.push("Acknowledgment");
        chapters.push("Acknowledgment");
        chapters.push("Acknowledgment");
        chapters.push("Acknowledgment");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword");
        chapters.push("Foreword"); //40 
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("1");
        chapters.push("Appendix 1.1");
        chapters.push("Appendix 1.1");
        chapters.push("Appendix 1.1");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("Appendix 1.2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("2");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("Appendix 2.1");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        chapters.push("3");
        //added missing unit
        chapters.push("3");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("4");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.1");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("Appendix 4.2");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        chapters.push("5");
        // adding missing unit
        chapters.push("5");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.1");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
        chapters.push("Appendix 5.2");
    }
    // technical debt
    // modifier
    function set(uint256 location, string calldata _unit) external {
        chapters[location] = _unit;
    }
    function getById(uint256 location) external override returns (string memory chapter) {
        return chapters[location];
    }
}